=== Lukc/fg-xsl-compo/compos.dtd
<!ELEMENT fleets (category*)>
<!ELEMENT category (name, compo*)>
<!ELEMENT compo (name, ships+, strength*, weakness*, note?)>
<!ATTLIST compo min-pow CDATA #IMPLIED>
<!ATTLIST compo min-tech CDATA #IMPLIED>
<!ATTLIST compo faction (Brotherhood|GalacticDiplomaticOffice|AutonomousNetwork|Hybrid) #IMPLIED>
<!ATTLIST compo type (aggressive|defensive|cargo|architect|mixed) "mixed">
<!ELEMENT name (#PCDATA)>
<!ELEMENT ships (front, back?)>
<!ATTLIST ships type (variation) #IMPLIED>
<!ATTLIST ships title CDATA #IMPLIED>
<!ELEMENT front (ship*)>
<!ELEMENT back (ship*)>
<!ELEMENT ship (#PCDATA)>
<!ATTLIST ship amount (-1|0|1|2|3|4|5|6) #REQUIRED>
<!ELEMENT strength (#PCDATA)>
<!ELEMENT weakness (#PCDATA)>
<!ELEMENT note (#PCDATA)>

=== Lukc/fg-xsl-compo/compos.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet href="compos.xsl" type="text/xsl" title="Default style"?>
<!DOCTYPE fleets PUBLIC "-//FGDOC//DTD FleetCompos XML//EN" "./compos.dtd">
<fleets>
	<category>
		<name>Generic</name>
		<compo min-tech="4" min-pow="1k">
			<name>CorséZéros</name>
			<ships title="Hellcats">
				<front>
					<ship amount="2">Corsairs</ship>
					<ship amount="2">Zeros</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="5">Sentinels</ship>
				</back>
			</ships>
			<ships type="variation" title="Banshees">
				<front>
					<ship amount="2">Corsairs</ship>
					<ship amount="2">Zeros</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Banshees</ship>
					<ship amount="5">Sentinels</ship>
				</back>
			</ships>
		</compo>
		<compo min-pow="40k" type="generic">
			<name>Isha-one</name>
			<ships title="Hades">
				<front>
					<ship amount="5">Trinities</ship>
					<ship amount="3">Blades</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="2">Hades</ship>
				</back>
			</ships>
			<ships type="variation" title="Spectres">
				<front>
					<ship amount="5">Trinities</ship>
					<ship amount="3">Blades</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="2">Spectres</ship>
				</back>
			</ships>
			<ships type="variation" title="Furies">
				<front>
					<ship amount="5">Trinities</ship>
					<ship amount="3">Blades</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="2">Furies</ship>
				</back>
			</ships>
			<note>Contribution d’Ishamael pour 40k et 70k. :)</note>
		</compo>
		<compo min-pow="5k" type="aggressive">
			<name>Isha-two</name>
			<ships>
				<front>
					<ship amount="3">Blades</ship>
					<ship amount="4">Banshees</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="2">Furies</ship>
				</back>
			</ships>
			<strength>Sentinels</strength>
		</compo>
		<compo min-tech="8" min-pow="1k" type="aggressive">
			<name>When I Don't Know</name>
			<ships>
				<front>
					<ship amount="2">Predators</ship>
					<ship amount="2">Blades</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="4">Sentinels</ship>
					<ship amount="1">Spectres</ship>
				</back>
			</ships>
		</compo>
		<compo min-tech="5" min-pow="10k" type="aggressive">
			<name>When I Didn't Know</name>
			<ships>
				<front>
					<ship amount="5">Hellcats</ship>
					<ship amount="3">Blades</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="2">Spectres</ship>
					<ship amount="2">Raptors</ship>
				</back>
			</ships>
		</compo>
	</category>
	<category>
		<name>Defensive fleets</name>
		<compo min-tech="8" min-pow="20k" type="defensive">
			<name>Shield</name>
			<ships>
				<front>
					<ship amount="2">Templars</ship>
					<ship amount="2">Eclipses</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Sentinels</ship>
					<ship amount="2">Valkiries</ship>
				</back>
			</ships>
			<weakness>Full Spectre</weakness>
		</compo>
		<compo min-tech="5" min-pow="500" type="cargo">
			<name>Survivor</name>
			<ships>
				<front>
					<ship amount="-1">Orions</ship>
				</front>
			</ships>
			<strength>Shep fleets</strength>
			<weakness>Anti-cargos</weakness>
		</compo>
		<compo min-tech="6" min-pow="2k" type="defensive">
			<name>Soban tank</name>
			<ships>
				<front>
					<ship amount="2">Paladins</ship>
					<ship amount="2">Spectres</ship>
					<ship amount="3">Banshees</ship>
				</front>
				<back>
					<ship amount="2">Valkiries</ship>
					<ship amount="4">Sentinels</ship>
				</back>
			</ships>
		</compo>
	</category>
	<category>
		<name>Brutal fleets</name>
		<compo min-tech="4" min-pow="1k" type="aggressive">
			<name>Full Spectres</name>
			<ships>
				<front>
					<ship amount="1">Spectres</ship>
					<ship amount="3">Blades</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Sentinels</ship>
					<ship amount="5">Shadows</ship>
				</back>
			</ships>
			<ships type="variation" title="Occultation">
				<front>
					<ship amount="2">Spectres</ship>
					<ship amount="5">Gardians</ship>
					<ship amount="3">Blades</ship>
				</front>
				<back>
					<ship amount="5">Shadows</ship>
					<ship amount="6">Eclipses</ship>
				</back>
			</ships>
			<strength>Full Oblivion</strength>
			<weakness>Sentinels</weakness>
			<note>Mettre plus de blades et très peu de gardiens en 20k+.</note>
		</compo>
		<compo min-pow="5k" type="aggressive">
			<name>Full Raptors</name>
			<ships>
				<front>
					<ship amount="4">Banshees</ship>
					<ship amount="3">Blades</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="2">Raptors</ship>
				</back>
			</ships>
		</compo>
		<compo type="aggressive">
			<name>Hurricane power</name>
			<ships>
				<front>
					<ship amount="3">Hurricanes</ship>
					<ship amount="3">Blades</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Sentinels</ship>
					<ship amount="2">Protectors</ship>
				</back>
			</ships>
			<ships type="variation" title="Shadows (Brotherhood)">
				<front>
					<ship amount="3">Hurricanes</ship>
					<ship amount="3">Blades</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Shadows</ship>
					<ship amount="2">Protectors</ship>
				</back>
			</ships>
			<note>Chargez les hurricanes en défense tout les 2 tours, et inversez les bonus/malus d’attaque et de défense des hurricanes avec les protecteurs en fin de combat pour bénéficier d’une attaque importante en ayant pris des dégâts réduits pendant le reste du combat.</note>
			<note>Contribution d’Ishamael.</note>
		</compo>
		<compo min-pow="5k" type="aggressive">
			<name>Full Recons</name>
			<ships>
				<front>
					<ship amount="3">Templars</ship>
					<ship amount="3">Blades</ship>
					<ship amount="3">Banshees</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="2">Recons</ship>
				</back>
			</ships>
			<ships type="variation" title="Paladins">
				<front>
					<ship amount="3">Templars</ship>
					<ship amount="3">Blades</ship>
					<ship amount="3">Paladins</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="2">Recons</ship>
				</back>
			</ships>
			<ships type="variation" title="Low-tech">
				<front>
					<ship amount="4">Sentinels</ship>
					<ship amount="2">Corsairs</ship>
					<ship amount="2">Zeros</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="2">Recons</ship>
				</back>
			</ships>
			<strength>Raiders</strength>
			<note>Recons can be replaced by Recon Falcons.</note>
		</compo>
		<compo min-tech="6" min-pow="5k" type="aggressive">
			<name>Full Styx</name>
			<ships>
				<front>
					<ship amount="4">Templars</ship>
					<ship amount="5">Spectres</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Sentinels</ship>
					<ship amount="1">Styx</ship>
				</back>
			</ships>
			<strength>Full Fury</strength>
			<weakness>Full Spectres</weakness>
			<weakness>Brutal fleets</weakness>
		</compo>
		<compo min-pow="5k" type="aggressive">
			<name>Full Fury</name>
			<ships>
				<front>
					<ship amount="4">Templars</ship>
					<ship amount="5">Spectres</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="4">Hellcats</ship>
					<ship amount="1">Furies</ship>
				</back>
			</ships>
			<weakness>Full Styx</weakness>
		</compo>
		<compo min-pow="5k" type="aggressive">
			<name>Full Hades</name>
			<ships>
				<front>
					<ship amount="3">Blades</ship>
					<ship amount="4">Banshees</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="2">Hades</ship>
				</back>
			</ships>
			<strength>Cruisers</strength>
			<note>Suicidaire au dessus de 10k.</note>
		</compo>
		<compo type="aggressive">
			<name>Anti-cargos</name>
			<ships>
				<front>
					<ship amount="6">Hellcats</ship>
					<ship amount="1">Recons</ship>
					<ship amount="6">Corsairs</ship>
					<ship amount="6">Styx</ship>
				</front>
			</ships>
			<strength>Survivor</strength>
			<weakness>Anything else</weakness>
		</compo>
		<compo type="aggressive">
			<name>Anti-raiders</name>
			<ships>
				<front>
					<ship amount="6">Templars</ship>
					<ship amount="6">Hellcats</ship>
					<ship amount="1">Paladins</ship>
				</front>
				<back>
					<ship amount="5">Corsairs</ship>
				</back>
			</ships>
			<strength>Raiders</strength>
			<weakness>Anything else</weakness>
			<note>Tested by Lukc, may be improved for resilience.</note>
		</compo>
		<compo type="aggressive" faction="Brotherhood">
			<name>Low level</name>
			<ships>
				<front>
					<ship amount="1">Corsairs</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="5">Hellcats</ship>
					<ship amount="5">Shadows</ship>
				</back>
			</ships>
			<strength>Low level AI</strength>
		</compo>
	</category>
	<category>
		<name>Versus</name>
		<compo min-tech="8" faction="Brotherhood" type="aggressive">
			<name>Anti-minatoi PalaSpectres</name>
			<ships>
				<front>
					<ship amount="2">Furies</ship>
					<ship amount="2">Predators</ship>
					<ship amount="5">Guardians</ship>
				</front>
				<back>
					<ship amount="3">Shadows</ship>
					<ship amount="3">Sentinels</ship>
				</back>
			</ships>
			<strength>Banshees</strength>
			<strength>Tigers</strength>
